### ISSUE TITLE
Acrylic Upper Mid Plate Is Missing Space For Switch Teeth

### ISSUE THREAD

**Issue by jngls** [gtips/reviung#9]
The [sandwiched upper mid acrylic plate](https://github.com/gtips/reviung/tree/master/reviung41/acrylic-plate/upper-middle-plate) contains no space in the 14x14mm switch holes for the switch panel mount teeth to grip onto the FR4 top plate. So the switches may fall out, especially when removing keycaps.

I've hacked together an STL with some cutouts (shown below) which has enabled me to print my own upper mid plate, but sadly I don't have Illustrator, so can't submit a PR to correct the issue at source.

I'd like to suggest that something like the cutouts shown below is applied to the Reviung upper mid plate, so that the switches can grip the FR4 correctly.

![image](https://user-images.githubusercontent.com/12872500/191804319-f23b08aa-65e2-45b6-a3d3-d01323445eac.png)

**Comment by gtips** [comment]
I've been away from GitHub for a while.
Sorry for the late response.

Thanks for the suggestion.
https://github.com/gtips/reviung/tree/master/reviung41/acrylic-plate/upper-middle-plate/ver1.1
In this version, the switch hole is 14.9mm north-south, with 0.9mm of space left. So there is space for the switch tabs.
But the switch hole in your suggestion is cool.

**Comment by jngls** [comment]
NP I must have had the older version then. Cheers, let's close this.
